server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qiu.domain
  